steps:
  # Build the container image - atrux-back-end is the name of project
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/atrux-back-end', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/atrux-back-end']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy',  'atrux-back-end', '--image', 'gcr.io/$PROJECT_ID/atrux-back-end',  '--region', 'us-central1', '--platform', 'managed',
           '--allow-unauthenticated']
images:
  - 'gcr.io/$PROJECT_ID/atrux-back-end'